Feature/db challenge1
MunehiroMachida/quelcode-db pull request #1
Opened 2020-06-30 07:50 UTC by MunehiroMachida

DB課題１です。
よろしくお願いします。

2020-07-01 02:54 UTC, yusaku-inamura requested changes
みました〜🙆‍♂️ 
それなりに要件抑えられていて悪くないのですが、所々気になる点があったのでコメントしてます。
特に `なにも知らない第三者に見せた時` にDB構造を認識齟齬なく伝えられるか?を意識するとよりぐっどですね  👍 

下記の点について確認及び修正お願いします。

- チャットルームテーブルに参加日時を持たせていますが、これはつまり該当のルームに誰かが入るたびに参加日時が更新される=最終参加者の参加日時を登録するということでしょうか?本当に要件を満たすことができる構造になっているか確認してみましょう。
- `ダイレクトチャット` 、`ファイル送信` などそれ単体では何を表してるのかわからない論理名がちらほら見受けられます。入るデータの性質に合わせたもっと具体的な名前をつけましょう。同様の項目が他にもないか確認して修正に挑戦してみてください。
- `論理削除` という名前のカラムが存在しますが、そもそも削除を表す項目が用意されている時点で論理削除のため、あまりそのような名前をつけるのは一般的ではないかもしれません。一個前の指摘の一部においてのヒントにもなりますが、単純なon、offを表す時に使用する一般的な名称があったはず・・・！
- 投稿テーブルの `添付ファイル` とはなんでしょう?場合によってはバイナリでファイルをDBに直接保存する用のカラムなのではないか？など認識齟齬の原因になりそうですね。こちらも具体的な名前をつけましょう。

2020-07-02 06:43 UTC, piasoratech requested changes
個人的な好みの部分もありますが、以下を修正してください。
- 各テーブルの最後のカラムは日時系のカラムにしましょう。
あと、こちらは修正しなくても良いですが各テーブルの作成者、更新者のidは一応外部キーであることを認識しておいてください。

2020-07-02 09:43 UTC, piasoratech requested changes
投稿テーブルだけ直っていないので、修正をお願いします！

2020-07-02 12:18 UTC, MunehiroMachida commented
> 投稿テーブルだけ直っていないので、修正をお願いします！

これは本当にすみません。

2020-07-03 02:32 UTC, Yuzunoha approved these changes
OKです！！！承認しました！！！！！

修正不要ですが今テーブルのタイトル欄に主キーを書いちゃっていますね。
vscodeの左の検索バーから`er`で検索して`ER Table 1`とかの部品を使うとよいです！！

![image](https://user-images.githubusercontent.com/22877094/86425553-75223280-bd20-11ea-84d3-a955c549e09c.png)

2020-07-06 00:12 UTC, merged